// DentiFlow Speed-to-Lead — Database Types
//
// Database interface: re-exported from supabase.ts (auto-generated by `npx supabase gen types`)
// Custom interfaces: kept here for stricter typing (union types, explicit casts)
//
// To regenerate: npx supabase gen types typescript --linked > src/types/supabase.ts

export { type Database } from './supabase';

export interface Practice {
  id: string;
  name: string;
  owner_name: string | null;
  phone: string | null;
  email: string | null;
  website: string | null;
  address: string | null;
  city: string | null;
  state: string | null;
  timezone: string;
  booking_platform: string;
  booking_url: string | null;
  google_review_link: string | null;
  brand_voice: string;
  twilio_phone: string | null;
  practice_config: PracticeConfig;
  business_hours: BusinessHours;
  appointment_buffer_minutes: number;
  active: boolean;
  recall_llm_enabled?: boolean;
  created_at: string;
  updated_at: string;
}

export interface PracticeConfig {
  services_offered?: string[];
  pricing_overrides?: Record<string, PricingOverride>;
  providers?: Provider[];
  tone_notes?: string;
  booking_notes?: string;
  insurance_note?: string;
  new_patient_special?: string;
  // Review & referral config
  google_review_url?: string;
  referral_offer?: string;
  referral_incentive?: string;
  review_survey_delay_hours?: number;
}

export interface PricingOverride {
  low: number;
  high: number;
  unit: string;
  notes?: string;
}

export interface Provider {
  name: string;
  title: string;
  specialties: string[];
}

export interface BusinessHours {
  monday: DayHours | null;
  tuesday: DayHours | null;
  wednesday: DayHours | null;
  thursday: DayHours | null;
  friday: DayHours | null;
  saturday: DayHours | null;
  sunday: DayHours | null;
}

export interface DayHours {
  open: string;
  close: string;
}

export type PatientStatus = 'new' | 'contacted' | 'nurturing' | 'booked' | 'no_show' | 'completed' | 'inactive';
export type PatientType = 'new_patient' | 'existing_patient' | 'unknown';
export type PatientSource = 'web_form' | 'sms' | 'missed_call' | 'email' | 'chat' | 'manual' | 'google_ads' | 'referral';

export interface Patient {
  id: string;
  practice_id: string;
  first_name: string | null;
  last_name: string | null;
  phone: string | null;
  email: string | null;
  source: PatientSource;
  status: PatientStatus;
  interested_service: string | null;
  patient_type: PatientType;
  last_visit_date: string | null;
  lead_score: number;
  tags: string[];
  metadata: Record<string, unknown>;
  notes: string | null;
  location: string | null;
  // PMS integration
  pms_patient_id: string | null;
  // Recall fields
  recall_eligible: boolean;
  recall_opt_out: boolean;
  recall_voice: string | null;
  recall_segment: string | null;
  created_at: string;
  updated_at: string;
}

export type Channel = 'sms' | 'email' | 'web_form' | 'chat' | 'phone';
export type Direction = 'inbound' | 'outbound';
export type AutomationType = 'speed_to_lead' | 'nurture' | 'reminder' | 'recall' | 'review_request' | null;

export interface Conversation {
  id: string;
  practice_id: string;
  patient_id: string;
  channel: Channel;
  direction: Direction;
  message_body: string;
  service_context: string | null;
  ai_generated: boolean;
  automation_type: AutomationType;
  status: string;
  twilio_sid: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export type AppointmentStatus = 'scheduled' | 'confirmed' | 'completed' | 'no_show' | 'cancelled' | 'rescheduled';
export type AppointmentSource = 'ai_booked' | 'manual' | 'booking_link' | 'phone';

export interface Appointment {
  id: string;
  practice_id: string;
  patient_id: string;
  service_id: string;
  provider_name: string | null;
  appointment_time: string;
  duration_minutes: number;
  status: AppointmentStatus;
  source: AppointmentSource | null;
  booking_platform_id: string | null;
  estimated_revenue: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface MetricsDaily {
  id: string;
  practice_id: string;
  date: string;
  new_leads: number;
  leads_contacted: number;
  appointments_booked: number;
  messages_sent: number;
  avg_response_time_ms: number;
  total_responses: number;
  under_60s_count: number;
  estimated_revenue_recovered: number;
  // Recall metrics
  recall_sent: number;
  recall_replies: number;
  recall_booked: number;
  recall_opt_outs: number;
  // Review metrics
  review_surveys_sent: number;
  review_scores_received: number;
  review_links_sent: number;
  referrals_generated: number;
  referrals_converted: number;
  // No-show metrics
  noshow_total: number;
  noshow_recovered: number;
  // PMS sync metrics
  pms_events_processed: number;
  // Booking link metrics (migration 008)
  recall_links_clicked: number;
  created_at: string;
}

export type AutomationResult = 'triggered' | 'sent' | 'delivered' | 'failed' | 'blocked';

export interface AutomationLog {
  id: string;
  practice_id: string;
  patient_id: string | null;
  automation_type: string;
  action: string | null;
  result: AutomationResult;
  response_time_ms: number | null;
  message_body: string | null;
  service_context: string | null;
  error_message: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
}

export interface UserProfile {
  id: string;
  auth_user_id: string;
  practice_id: string;
  role: string;
  created_at: string;
}

// Recall sequence row type (inline to avoid import() in Database map)
export interface RecallSequenceRow {
  id: string;
  practice_id: string;
  patient_id: string;
  assigned_voice: string;
  segment_overdue: string;
  months_overdue: number;
  sequence_day: number;
  sequence_status: string;
  booking_stage: string;
  next_send_at: string | null;
  last_sent_at: string | null;
  template_id: string | null;
  offered_slots: unknown | null;
  selected_slot: unknown | null;
  patient_preferences: unknown | null;
  opt_out: boolean;
  defer_until: string | null;
  exit_reason: string | null;
  reply_count: number;
  // Booking link tracking (migration 008)
  booking_link_token: string | null;
  link_clicked_at: string | null;
  link_followup_sent: boolean;
  created_at: string;
  updated_at: string;
}

// Re-export the typed version for use in recall services
export type { RecallSequence, NoshowSequence } from './recall';

// Re-export review types
export type { ReviewSequence, ReviewFeedback, Referral } from './review';

// Re-export PMS types
export type { PmsIntegration, PmsSyncLogRow, PmsAppointmentEvent } from './pms';

// Review sequence row type
export interface ReviewSequenceRow {
  id: string;
  practice_id: string;
  patient_id: string;
  appointment_id: string | null;
  status: string;
  satisfaction_score: number | null;
  review_url_sent: boolean;
  referral_sent: boolean;
  survey_send_at: string | null;
  reminder_sent_at: string | null;
  review_requested_at: string | null;
  referral_sent_at: string | null;
  created_at: string;
  updated_at: string;
}

// Review feedback row type
export interface ReviewFeedbackRow {
  id: string;
  practice_id: string;
  patient_id: string;
  review_sequence_id: string;
  score: number;
  feedback_text: string;
  acknowledged: boolean;
  created_at: string;
}

// No-show sequence row type
export interface NoshowSequenceRow {
  id: string;
  practice_id: string;
  patient_id: string;
  appointment_id: string | null;
  status: string;
  message_count: number;
  booking_stage: string;
  reply_count: number;
  offered_slots: unknown | null;
  selected_slot: unknown | null;
  patient_preferences: unknown | null;
  next_send_at: string | null;
  last_sent_at: string | null;
  defer_until: string | null;
  created_at: string;
  updated_at: string;
}

// Referral row type
export interface ReferralRow {
  id: string;
  practice_id: string;
  referring_patient_id: string;
  referred_name: string | null;
  referred_phone: string | null;
  referral_link_hash: string;
  status: string;
  converted_at: string | null;
  created_at: string;
}

// PMS integration row type
export interface PmsIntegrationRow {
  id: string;
  practice_id: string;
  pms_type: string;
  client_id: string | null;
  client_secret: string | null;
  access_token: string | null;
  refresh_token: string | null;
  token_expires_at: string | null;
  api_base_url: string | null;
  webhook_secret: string | null;
  webhook_api_key: string | null;
  polling_enabled: boolean;
  polling_interval_minutes: number;
  last_synced_at: string | null;
  sync_noshow: boolean;
  sync_complete: boolean;
  sync_cancelled: boolean;
  sync_rescheduled: boolean;
  active: boolean;
  last_error: string | null;
  error_count: number;
  created_at: string;
  updated_at: string;
}

// PMS sync log row type
export interface PmsSyncLogRowDb {
  id: string;
  practice_id: string;
  pms_event_id: string;
  pms_appointment_id: string;
  pms_patient_id: string | null;
  event_type: string;
  source: string;
  action_taken: string | null;
  dentiflow_appointment_id: string | null;
  dentiflow_patient_id: string | null;
  success: boolean;
  error_message: string | null;
  processed_at: string;
}

// Note: Database interface is now in supabase.ts (auto-generated).
// Custom Row interfaces above are kept for explicit typing/casting in service code.
